apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoExternalServices
metadata:
  name: no-internet-services
spec:
  parameters:
    internalCIDRs: ["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16"]
